version: '3'

services:
  front-end:
    build: ./front-end
    ports:
      - "3000:3000"  # Expose front-end on port 3000
    networks:
      - my-network

  back-end:
    build: ./back-end
    ports:
      - "5000:5000"  # Expose back-end on port 5000
    networks:
      - my-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx configuration
      - ./proxy.conf:/etc/nginx/conf.d/proxy.conf  # Custom proxy configuration
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
